action_id: trunk-upgrade-available
date: 2024-03-30 03:21:13
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\DXe3Q.yaml for details.
  error_path: C:\Users\Admin\Documents\MLAI\CSCN8010-labs\.trunk\out\DXe3Q.yaml
timestamp: 1711768873
full_timestamp:
  nanos: 567133000
  seconds: 1711768873
trunk_version: 1.21.0
